// Generated by CoffeeScript 1.6.2
var jsdom, walk;

jsdom = require('jsdom');

walk = function(node) {
  var _results;

  node = node.firstChild;
  _results = [];
  while (node) {
    walk(node);
    _results.push(node = node.nextSibling);
  }
  return _results;
};

jsdom.env('letter-view.nxt', function(errors, window) {
  return walk(window.document);
});
